#Jekyll configuration
name: Anagram Palindrome - Fajar BC GitHub
description: Check if text contain anagram pattern, check if two words are anagram, check if word is palindrome.<br><a href="https://fajarbc.github.io/anagram-palindrome/CHANGELOG.html">Changlog</a><br><a href="https://fajarbc.github.io/anagram-palindrome/docs/index.html">API Documentation</a>
markdown: GFM
show_downloads: false
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
