#Jekyll configuration
name: Anagram Palindrome - Fajar BC GitHub
description: Check if text contain anagram pattern, check if two words are anagram, check if word is palindrome
markdown: GFM
theme: minimal
show_downloads: false
